### PR TITLE
add support for UpdateCustomerPaymentProfileRequest endpoint

### PR DESCRIPTION
**Pull request by KCErb**
Please let me know what I can do to get this in as soon as possible. I need it for my project. 

Thanks for the great library! :)

### CODE REVIEW

**Comment by KCErb** [comment]
I'm not sure I understand the build failures. My local run of phpunit passed, but the log seems to be complaining about whitespace. I'm not familiar with this system so I'm not sure if that's the error that's causing it to fail. I believe I matched the whitespace to what you guys already have. Please let me know what I missed if you can. Thanks again :)

**Comment by mglaman** [comment]
Hey, thanks for PR! I can give it a look over. If it's phpcs I can tweak up
before merger.

Thanks for this, got missed in initial SDK hustle.

**Comment by mglaman** [comment]
Yep, just because space is 2 instead of 4 (to match PSR-2). I can fixup for merge no problem

**Comment by KCErb** [comment]
Thanks for the quick response, the library was well architected so it was a piece of cake. Since I already have this ready to push, I could just fix it here. OK by you? (We're just talking about the new class right?)

**Comment by mglaman** [comment]
Yeah, go ahead. The Travis output says which and where. If you install
phpcs and actually run `phpcbf --standard=psr-2`, I believe it is, and it
can autofix it

**Comment by KCErb** [comment]
Hmm, those failures are interesting. When I ran locally, I would see those methods (not ones that I touched by the way so I hope I didn't break them 😬 ) fail 1 in 5 times or so. It seems kinda sporadic. Perhaps you guys know more about that?

**Comment by mglaman** [comment]
Out for a walk, realized main branch is failing. Maybe I committed the
failure way back

**Comment by mglaman** [comment]
Thanks for the PR! Merged!

**Comment by KCErb** [comment]
Awesome, thanks for the quick turn around!

**Pull request merged**
