### PR TITLE
Create Tax data type

### PR DESCRIPTION
**Pull request by lisastreeter**

### CODE REVIEW

**Comment by mglaman** [comment]
@lisastreeter could we add this to a transaction request test?

**Comment by mglaman** [comment]
```
1) CommerceGuys\AuthNet\Tests\CreateTransactionRequest\AuthCaptureTest::testAuthCaptureTransaction
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'I00001'
+'E00027'
```

I think it's due to calling `toArray` and not passing the object itself.

**Comment by mglaman** [comment]
@lisastreeter ah so the problem was needed rounded amount for price?

**Comment by lisastreeter** [comment]
I think it's still failing. The Authorize.net API says up to 4 decimal places is good but since I was only testing it (manually) using 2, I thought I'd try changing the test to just 2.

**Comment by lisastreeter** [comment]
Couldn't think of anything else to try. The test code matches what I'm doing in the commerce_authnet code that works.

**Comment by mglaman** [comment]
@lisastreeter I just fixed the phpcs warnings on `master`. Scrutinizer just timed out in phpunit somehow. Which is why TravisCI was failing.

**Comment by lisastreeter** [comment]
Oh, then maybe I should go back to 4 decimal places. I think the actual bug was that I was setting the amount as a string instead of a number.

**Comment by mglaman** [comment]
That could have been it. Serialized as wrong format.

**Comment by mglaman** [comment]
Debugged locally,

```
                    [errors] => stdClass Object
                        (
                            [error] => stdClass Object
                                (
                                    [errorCode] => 76
                                    [errorText] => The tax amount is invalid.
                                )

                        )
```

**Comment by mglaman** [comment]
Yep, `'amount' => 5.4321,` fails but `'amount' => 5.43,` passes. Their API lies!

**Comment by lisastreeter** [comment]
Ha! Interesting. Guess I'd better make sure I round the tax value to 2 decimal places in the commerce_authnet code. Thank you!

**Pull request merged**
